//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.STEEL_GG {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtINTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_DEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtHD;
		protected global::System.Web.UI.WebControls.TextBox txtKD;
		protected global::System.Web.UI.WebControls.TextBox txtQUANTITY;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
