//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.STEEL_GG {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblINTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_NAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_DEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_INTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_NAME;
	protected global::System.Web.UI.WebControls.Label lblSPECIFICATIONS;
	protected global::System.Web.UI.WebControls.Label lblHD;
	protected global::System.Web.UI.WebControls.Label lblKD;
	protected global::System.Web.UI.WebControls.Label lblQUANTITY;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
