//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SAL_RECEIPT_MASTER {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBillNO;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_COMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtBillTYPE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtINSTOCK_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtINSTOCK_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtEMPLOYEE_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtEMPLOYEE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtBillDate;
		protected global::System.Web.UI.WebControls.TextBox txtBILL_STATUS;
		protected global::System.Web.UI.WebControls.TextBox txtPayAcount;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
