//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_PCMASTER {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBillNo;
	protected global::System.Web.UI.WebControls.Label lblBILL_DATE;
	protected global::System.Web.UI.WebControls.Label lblGROUP;
	protected global::System.Web.UI.WebControls.Label lblMACHINE;
	protected global::System.Web.UI.WebControls.Label lblFACTORY;
	protected global::System.Web.UI.WebControls.Label lblBILL_STATUS;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_CODE;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_NAME;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_CODE;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
