//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_SALE {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCompanyCode;
		protected global::System.Web.UI.WebControls.TextBox txtEmployeCode;
		protected global::System.Web.UI.WebControls.TextBox txtEmployeeName;
		protected global::System.Web.UI.WebControls.TextBox txtDepartmentCode;
		protected global::System.Web.UI.WebControls.TextBox txtEmployeeType;
		protected global::System.Web.UI.WebControls.TextBox txtIDCardNo;
		protected global::System.Web.UI.WebControls.TextBox txtSociatyNo;
		protected global::System.Web.UI.WebControls.TextBox txtSensusData;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtBirthDay;
		protected global::System.Web.UI.WebControls.TextBox txtDegree;
		protected global::System.Web.UI.WebControls.TextBox txtDegreeCard;
		protected global::System.Web.UI.WebControls.TextBox txtHealth;
		protected global::System.Web.UI.WebControls.TextBox txtHealthDate;
		protected global::System.Web.UI.WebControls.TextBox txtSpinsterhood;
		protected global::System.Web.UI.WebControls.TextBox txtSpinsterhoodDate;
		protected global::System.Web.UI.WebControls.TextBox txtIdleness;
		protected global::System.Web.UI.WebControls.TextBox txtIdlenessDate;
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtArrialDay;
		protected global::System.Web.UI.WebControls.TextBox txtLeaveDay;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtZip;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtAllowUsed;
		protected global::System.Web.UI.WebControls.TextBox txtSociatyCode;
		protected global::System.Web.UI.WebControls.TextBox txtSociatyDate;
		protected global::System.Web.UI.WebControls.TextBox txtSociatyPay;
		protected global::System.Web.UI.WebControls.TextBox txtIndiSWBX;
		protected global::System.Web.UI.WebControls.TextBox txtIndiSYBX;
		protected global::System.Web.UI.WebControls.TextBox txtSociatyComp;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtEmployeNo;
		protected global::System.Web.UI.WebControls.TextBox txtWorkID;
		protected global::System.Web.UI.WebControls.TextBox txtSituations;
		protected global::System.Web.UI.WebControls.TextBox txtHospitalPay;
		protected global::System.Web.UI.WebControls.TextBox txtHospitalDate;
		protected global::System.Web.UI.WebControls.TextBox txtContract;
		protected global::System.Web.UI.WebControls.TextBox txtContractDate;
		protected global::System.Web.UI.WebControls.TextBox txtPayMounth;
		protected global::System.Web.UI.WebControls.TextBox txtIsZB;
		protected global::System.Web.UI.WebControls.TextBox txtIsBD;
		protected global::System.Web.UI.WebControls.TextBox txtLastEdit;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
