//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_SALE {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCompanyCode;
	protected global::System.Web.UI.WebControls.Label lblEmployeCode;
	protected global::System.Web.UI.WebControls.Label lblEmployeeName;
	protected global::System.Web.UI.WebControls.Label lblDepartmentCode;
	protected global::System.Web.UI.WebControls.Label lblEmployeeType;
	protected global::System.Web.UI.WebControls.Label lblIDCardNo;
	protected global::System.Web.UI.WebControls.Label lblSociatyNo;
	protected global::System.Web.UI.WebControls.Label lblSensusData;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblBirthDay;
	protected global::System.Web.UI.WebControls.Label lblDegree;
	protected global::System.Web.UI.WebControls.Label lblDegreeCard;
	protected global::System.Web.UI.WebControls.Label lblHealth;
	protected global::System.Web.UI.WebControls.Label lblHealthDate;
	protected global::System.Web.UI.WebControls.Label lblSpinsterhood;
	protected global::System.Web.UI.WebControls.Label lblSpinsterhoodDate;
	protected global::System.Web.UI.WebControls.Label lblIdleness;
	protected global::System.Web.UI.WebControls.Label lblIdlenessDate;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblArrialDay;
	protected global::System.Web.UI.WebControls.Label lblLeaveDay;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblZip;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblAllowUsed;
	protected global::System.Web.UI.WebControls.Label lblSociatyCode;
	protected global::System.Web.UI.WebControls.Label lblSociatyDate;
	protected global::System.Web.UI.WebControls.Label lblSociatyPay;
	protected global::System.Web.UI.WebControls.Label lblIndiSWBX;
	protected global::System.Web.UI.WebControls.Label lblIndiSYBX;
	protected global::System.Web.UI.WebControls.Label lblSociatyComp;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblEmployeNo;
	protected global::System.Web.UI.WebControls.Label lblWorkID;
	protected global::System.Web.UI.WebControls.Label lblSituations;
	protected global::System.Web.UI.WebControls.Label lblHospitalPay;
	protected global::System.Web.UI.WebControls.Label lblHospitalDate;
	protected global::System.Web.UI.WebControls.Label lblContract;
	protected global::System.Web.UI.WebControls.Label lblContractDate;
	protected global::System.Web.UI.WebControls.Label lblPayMounth;
	protected global::System.Web.UI.WebControls.Label lblIsZB;
	protected global::System.Web.UI.WebControls.Label lblIsBD;
	protected global::System.Web.UI.WebControls.Label lblLastEdit;


       
    }
}
