//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_ZXGG {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtINTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtZXXXCode;
		protected global::System.Web.UI.WebControls.TextBox txtZXXXName;
		protected global::System.Web.UI.WebControls.TextBox txtZXKDGS;
		protected global::System.Web.UI.WebControls.TextBox txtZXLENGS;
		protected global::System.Web.UI.WebControls.TextBox txtZXZK;
		protected global::System.Web.UI.WebControls.TextBox txtZXDT;
		protected global::System.Web.UI.WebControls.TextBox txtZXZBSL;
		protected global::System.Web.UI.WebControls.TextBox txtZXYZBJ;
		protected global::System.Web.UI.WebControls.TextBox txtZXGZBJ;
		protected global::System.Web.UI.WebControls.TextBox txtZXIMAGE;
		protected global::System.Web.UI.WebControls.TextBox txtZXZK_cm;
		protected global::System.Web.UI.WebControls.TextBox txtZXDT_cm;
		protected global::System.Web.UI.WebControls.TextBox txtZXYxgs;
		protected global::System.Web.UI.WebControls.TextBox txtZXYXGD;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
