//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_ZXGG {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblINTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_NAME;
	protected global::System.Web.UI.WebControls.Label lblZXXXCode;
	protected global::System.Web.UI.WebControls.Label lblZXXXName;
	protected global::System.Web.UI.WebControls.Label lblZXKDGS;
	protected global::System.Web.UI.WebControls.Label lblZXLENGS;
	protected global::System.Web.UI.WebControls.Label lblZXZK;
	protected global::System.Web.UI.WebControls.Label lblZXDT;
	protected global::System.Web.UI.WebControls.Label lblZXZBSL;
	protected global::System.Web.UI.WebControls.Label lblZXYZBJ;
	protected global::System.Web.UI.WebControls.Label lblZXGZBJ;
	protected global::System.Web.UI.WebControls.Label lblZXIMAGE;
	protected global::System.Web.UI.WebControls.Label lblZXZK_cm;
	protected global::System.Web.UI.WebControls.Label lblZXDT_cm;
	protected global::System.Web.UI.WebControls.Label lblZXYxgs;
	protected global::System.Web.UI.WebControls.Label lblZXYXGD;
	protected global::System.Web.UI.WebControls.Label lblIMAGE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;


       
    }
}
