//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_SEND_SHD {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBillNo;
		protected global::System.Web.UI.WebControls.TextBox txtBILL_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPCBH;
		protected global::System.Web.UI.WebControls.TextBox txtCLBH;
		protected global::System.Web.UI.WebControls.TextBox txtSHJE;
		protected global::System.Web.UI.WebControls.TextBox txtTHJE;
		protected global::System.Web.UI.WebControls.TextBox txtHZJE;
		protected global::System.Web.UI.WebControls.TextBox txtLWKKJE;
		protected global::System.Web.UI.WebControls.TextBox txtYSJE;
		protected global::System.Web.UI.WebControls.TextBox txtAccepter;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
