//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_SEND_SHD {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBillNo;
	protected global::System.Web.UI.WebControls.Label lblBILL_DATE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_NAME;
	protected global::System.Web.UI.WebControls.Label lblPCBH;
	protected global::System.Web.UI.WebControls.Label lblCLBH;
	protected global::System.Web.UI.WebControls.Label lblSHJE;
	protected global::System.Web.UI.WebControls.Label lblTHJE;
	protected global::System.Web.UI.WebControls.Label lblHZJE;
	protected global::System.Web.UI.WebControls.Label lblLWKKJE;
	protected global::System.Web.UI.WebControls.Label lblYSJE;
	protected global::System.Web.UI.WebControls.Label lblAccepter;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
