//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_SUPPLY {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtINTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_SUPPLY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtTypeCode;
		protected global::System.Web.UI.WebControls.TextBox txtTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtTELPHONE;
		protected global::System.Web.UI.WebControls.TextBox txtTELPHONE1;
		protected global::System.Web.UI.WebControls.TextBox txtFAX;
		protected global::System.Web.UI.WebControls.TextBox txtEMAIL;
		protected global::System.Web.UI.WebControls.TextBox txtFULLNAME;
		protected global::System.Web.UI.WebControls.TextBox txtADDRESS;
		protected global::System.Web.UI.WebControls.TextBox txtEASYCODE;
		protected global::System.Web.UI.WebControls.TextBox txtContact_MAN;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.CheckBox chkALLOW_used;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
