//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SAL_ITEM_STOCK_DETAIL {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSTOCK_CODE;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_NAME;
	protected global::System.Web.UI.WebControls.Label lblITEM_INTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_NAME;
	protected global::System.Web.UI.WebControls.Label lblACTUAL_QTY;


       
    }
}
