//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_WGDETAIL {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblDetailID;
	protected global::System.Web.UI.WebControls.Label lblBillNO;
	protected global::System.Web.UI.WebControls.Label lblSequence;
	protected global::System.Web.UI.WebControls.Label lblItemInternalCode;
	protected global::System.Web.UI.WebControls.Label lblZXBJNO;
	protected global::System.Web.UI.WebControls.Label lblZXBJNAME;
	protected global::System.Web.UI.WebControls.Label lblQuantity;
	protected global::System.Web.UI.WebControls.Label lblFPqty;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
