//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.WL_DA_BOM {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSEQUENCE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_COLOR;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_ITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtSPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtMEASURE_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CZ;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_LH;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_LK;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_BJ;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_JZ;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_HZ;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_rate;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_GYLC;
		protected global::System.Web.UI.WebControls.TextBox txtNET_PRICE;
		protected global::System.Web.UI.WebControls.TextBox txtPRICE;
		protected global::System.Web.UI.WebControls.TextBox txtMIN_QTY;
		protected global::System.Web.UI.WebControls.TextBox txtMAX_QTY;
		protected global::System.Web.UI.WebControls.TextBox txtPOSITION;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtQuantity;
		protected global::System.Web.UI.WebControls.TextBox txtBARCODE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
