//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.WL_RECEIPT_MASTER {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBillNO;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_NAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_COMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_NAME;
	protected global::System.Web.UI.WebControls.Label lblBillTYPE;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_CODE;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_NAME;
	protected global::System.Web.UI.WebControls.Label lblINSTOCK_CODE;
	protected global::System.Web.UI.WebControls.Label lblINSTOCK_NAME;
	protected global::System.Web.UI.WebControls.Label lblEMPLOYEE_CODE;
	protected global::System.Web.UI.WebControls.Label lblEMPLOYEE_NAME;
	protected global::System.Web.UI.WebControls.Label lblBillDate;
	protected global::System.Web.UI.WebControls.Label lblBILL_STATUS;
	protected global::System.Web.UI.WebControls.Label lblPayAcount;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
