//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.WL_STOCK_DETAIL {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtACTUAL_QTY;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
