//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_USER {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblUSER_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUSER_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtdepartment;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_DEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.CheckBox chkPPRICE_SHOW;
		protected global::System.Web.UI.WebControls.TextBox txtPASSWORD;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtEmployeeCode;
		protected global::System.Web.UI.WebControls.TextBox txtAllowUsed;
		protected global::System.Web.UI.WebControls.TextBox txtisLicenceAudit;
		protected global::System.Web.UI.WebControls.TextBox txtUserType;
		protected global::System.Web.UI.WebControls.TextBox txtLastEdit;
		protected global::System.Web.UI.WebControls.TextBox txtAuditDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
