//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_USER {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUSER_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_NAME;
	protected global::System.Web.UI.WebControls.Label lblUSER_NAME;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_CODE;
	protected global::System.Web.UI.WebControls.Label lblSTOCK_NAME;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_NAME;
	protected global::System.Web.UI.WebControls.Label lbldepartment;
	protected global::System.Web.UI.WebControls.Label lblPARENT_DEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblPPRICE_SHOW;
	protected global::System.Web.UI.WebControls.Label lblPASSWORD;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblEmployeeCode;
	protected global::System.Web.UI.WebControls.Label lblAllowUsed;
	protected global::System.Web.UI.WebControls.Label lblisLicenceAudit;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblLastEdit;
	protected global::System.Web.UI.WebControls.Label lblAuditDate;


       
    }
}
