//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_COMPANY {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_FULLNAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_COMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtMANAGER;
		protected global::System.Web.UI.WebControls.TextBox txtADDRESS;
		protected global::System.Web.UI.WebControls.TextBox txtTELPHONE;
		protected global::System.Web.UI.WebControls.TextBox txtZIP;
		protected global::System.Web.UI.WebControls.TextBox txtEMAIL;
		protected global::System.Web.UI.WebControls.TextBox txtHTTP;
		protected global::System.Web.UI.WebControls.TextBox txtLICENSE;
		protected global::System.Web.UI.WebControls.TextBox txtREGISTER_BANK;
		protected global::System.Web.UI.WebControls.TextBox txtBANK_ACCOUNT;
		protected global::System.Web.UI.WebControls.TextBox txtALLOW_USED;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
