//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_COMPANY {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_NAME;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_FULLNAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_COMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblMANAGER;
	protected global::System.Web.UI.WebControls.Label lblADDRESS;
	protected global::System.Web.UI.WebControls.Label lblTELPHONE;
	protected global::System.Web.UI.WebControls.Label lblZIP;
	protected global::System.Web.UI.WebControls.Label lblEMAIL;
	protected global::System.Web.UI.WebControls.Label lblHTTP;
	protected global::System.Web.UI.WebControls.Label lblLICENSE;
	protected global::System.Web.UI.WebControls.Label lblREGISTER_BANK;
	protected global::System.Web.UI.WebControls.Label lblBANK_ACCOUNT;
	protected global::System.Web.UI.WebControls.Label lblALLOW_USED;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
