//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_SEND_DETAIL {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtDETAILID;
		protected global::System.Web.UI.WebControls.TextBox txtMASTERID;
		protected global::System.Web.UI.WebControls.TextBox txtBILLNO;
		protected global::System.Web.UI.WebControls.TextBox txtSequence;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_COLOR;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_ITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CD;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_KD;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_GD;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_SPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_MEASURE_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_GYLC;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_POSITION;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_MIN_QTY;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_MAX_QTY;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_IMAGE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_IMAGE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_DWMJ;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_BARCODE;
		protected global::System.Web.UI.WebControls.TextBox txtNET_PRICE;
		protected global::System.Web.UI.WebControls.TextBox txtPRICE;
		protected global::System.Web.UI.WebControls.TextBox txtQuantity;
		protected global::System.Web.UI.WebControls.TextBox txtORD_CGqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_CLqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_PCqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_WGqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_TCqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_WGZL;
		protected global::System.Web.UI.WebControls.TextBox txtORD_FPqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_Sendqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_SHqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_LHqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_HZqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_THqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_Acceptqty;
		protected global::System.Web.UI.WebControls.TextBox txtORD_TL;
		protected global::System.Web.UI.WebControls.TextBox txtORD_GRAPHICNO;
		protected global::System.Web.UI.WebControls.TextBox txtORD_SHDH;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
