//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_SEND_DETAIL {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblDETAILID;
	protected global::System.Web.UI.WebControls.Label lblMASTERID;
	protected global::System.Web.UI.WebControls.Label lblBILLNO;
	protected global::System.Web.UI.WebControls.Label lblSequence;
	protected global::System.Web.UI.WebControls.Label lblITEM_INTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_NAME;
	protected global::System.Web.UI.WebControls.Label lblITEM_COLOR;
	protected global::System.Web.UI.WebControls.Label lblPARENT_ITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_TYPE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CD;
	protected global::System.Web.UI.WebControls.Label lblITEM_KD;
	protected global::System.Web.UI.WebControls.Label lblITEM_GD;
	protected global::System.Web.UI.WebControls.Label lblITEM_SPECIFICATIONS;
	protected global::System.Web.UI.WebControls.Label lblITEM_MEASURE_UNIT;
	protected global::System.Web.UI.WebControls.Label lblITEM_GYLC;
	protected global::System.Web.UI.WebControls.Label lblITEM_POSITION;
	protected global::System.Web.UI.WebControls.Label lblITEM_MIN_QTY;
	protected global::System.Web.UI.WebControls.Label lblITEM_MAX_QTY;
	protected global::System.Web.UI.WebControls.Label lblITEM_IMAGE;
	protected global::System.Web.UI.WebControls.Label lblITEM_IMAGE_NAME;
	protected global::System.Web.UI.WebControls.Label lblITEM_DWMJ;
	protected global::System.Web.UI.WebControls.Label lblITEM_BARCODE;
	protected global::System.Web.UI.WebControls.Label lblNET_PRICE;
	protected global::System.Web.UI.WebControls.Label lblPRICE;
	protected global::System.Web.UI.WebControls.Label lblQuantity;
	protected global::System.Web.UI.WebControls.Label lblORD_CGqty;
	protected global::System.Web.UI.WebControls.Label lblORD_CLqty;
	protected global::System.Web.UI.WebControls.Label lblORD_PCqty;
	protected global::System.Web.UI.WebControls.Label lblORD_WGqty;
	protected global::System.Web.UI.WebControls.Label lblORD_TCqty;
	protected global::System.Web.UI.WebControls.Label lblORD_WGZL;
	protected global::System.Web.UI.WebControls.Label lblORD_FPqty;
	protected global::System.Web.UI.WebControls.Label lblORD_Sendqty;
	protected global::System.Web.UI.WebControls.Label lblORD_SHqty;
	protected global::System.Web.UI.WebControls.Label lblORD_LHqty;
	protected global::System.Web.UI.WebControls.Label lblORD_HZqty;
	protected global::System.Web.UI.WebControls.Label lblORD_THqty;
	protected global::System.Web.UI.WebControls.Label lblORD_Acceptqty;
	protected global::System.Web.UI.WebControls.Label lblORD_TL;
	protected global::System.Web.UI.WebControls.Label lblORD_GRAPHICNO;
	protected global::System.Web.UI.WebControls.Label lblORD_SHDH;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
