//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_YSJZ {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtFDID;
		protected global::System.Web.UI.WebControls.TextBox txtcustomcode;
		protected global::System.Web.UI.WebControls.TextBox txtcustomname;
		protected global::System.Web.UI.WebControls.TextBox txtSJJZ;
		protected global::System.Web.UI.WebControls.TextBox txtQZZK;
		protected global::System.Web.UI.WebControls.TextBox txtQZYS;
		protected global::System.Web.UI.WebControls.TextBox txtYSJE;
		protected global::System.Web.UI.WebControls.TextBox txtYSWS;
		protected global::System.Web.UI.WebControls.TextBox txtbegindate;
		protected global::System.Web.UI.WebControls.TextBox txtenddate;
		protected global::System.Web.UI.WebControls.TextBox txtcreatename;
		protected global::System.Web.UI.WebControls.TextBox txtcreatedate;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
