//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_YSJZ {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblFDID;
	protected global::System.Web.UI.WebControls.Label lblcustomcode;
	protected global::System.Web.UI.WebControls.Label lblcustomname;
	protected global::System.Web.UI.WebControls.Label lblSJJZ;
	protected global::System.Web.UI.WebControls.Label lblQZZK;
	protected global::System.Web.UI.WebControls.Label lblQZYS;
	protected global::System.Web.UI.WebControls.Label lblYSJE;
	protected global::System.Web.UI.WebControls.Label lblYSWS;
	protected global::System.Web.UI.WebControls.Label lblbegindate;
	protected global::System.Web.UI.WebControls.Label lblenddate;
	protected global::System.Web.UI.WebControls.Label lblcreatename;
	protected global::System.Web.UI.WebControls.Label lblcreatedate;
	protected global::System.Web.UI.WebControls.Label lblremark;


       
    }
}
