//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VIP_INFO {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtUSER_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtUSER_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtVIP_CARD_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtPASSWORD;
		protected global::System.Web.UI.WebControls.TextBox txtBEGIN_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtEND_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtVIP_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtTOTAL_SALES;
		protected global::System.Web.UI.WebControls.TextBox txtsalesno;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
