//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VIP_INFO {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblUSER_CODE;
	protected global::System.Web.UI.WebControls.Label lblUSER_NAME;
	protected global::System.Web.UI.WebControls.Label lblVIP_CARD_CODE;
	protected global::System.Web.UI.WebControls.Label lblVIP_TEMP_CARD_CODE;
	protected global::System.Web.UI.WebControls.Label lblPASSWORD;
	protected global::System.Web.UI.WebControls.Label lblBEGIN_DATE;
	protected global::System.Web.UI.WebControls.Label lblEND_DATE;
	protected global::System.Web.UI.WebControls.Label lblVIP_TYPE;
	protected global::System.Web.UI.WebControls.Label lblTOTAL_SALES;
	protected global::System.Web.UI.WebControls.Label lblsalesno;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
