//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_ITEM_PRICE {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCOLOR;
		protected global::System.Web.UI.WebControls.TextBox txtMeasureUnit;
		protected global::System.Web.UI.WebControls.TextBox txtPRICE;
		protected global::System.Web.UI.WebControls.TextBox txtSTART_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOP_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
