//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_SEND_MASTER {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMASTERID;
		protected global::System.Web.UI.WebControls.TextBox txtBILLNO;
		protected global::System.Web.UI.WebControls.TextBox txtMANUAL_BILLNO;
		protected global::System.Web.UI.WebControls.TextBox txtVehicle_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtVehicle_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtBILL_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtBILL_STATUS;
		protected global::System.Web.UI.WebControls.TextBox txtNOW_STATUS;
		protected global::System.Web.UI.WebControls.TextBox txtNOW_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSTOCK_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtFACTORY;
		protected global::System.Web.UI.WebControls.TextBox txtSALE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
