//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VEHICLE_ORD_DETAIL {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBillNo;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSALES_CONTRACTNO;
		protected global::System.Web.UI.WebControls.TextBox txtTRUCKER;
		protected global::System.Web.UI.WebControls.TextBox txtSEQUENCE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_ITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtMEASURE_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_COLOR;
		protected global::System.Web.UI.WebControls.TextBox txtNET_PRICE;
		protected global::System.Web.UI.WebControls.TextBox txtPRICE;
		protected global::System.Web.UI.WebControls.TextBox txtQTY;
		protected global::System.Web.UI.WebControls.TextBox txtQUANTITY;
		protected global::System.Web.UI.WebControls.TextBox txtACTUAL_QTY;
		protected global::System.Web.UI.WebControls.TextBox txtYKQUANTITY;
		protected global::System.Web.UI.WebControls.TextBox txtPAYAMOUNT;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPOSITION;
		protected global::System.Web.UI.WebControls.TextBox txtBARCODE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
		protected global::System.Web.UI.WebControls.TextBox txtDESCRIPTION;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
