//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VEHICLE_ORD_DETAIL {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblTempID;
	protected global::System.Web.UI.WebControls.Label lblBillNo;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_NAME;
	protected global::System.Web.UI.WebControls.Label lblSALES_CONTRACTNO;
	protected global::System.Web.UI.WebControls.Label lblTRUCKER;
	protected global::System.Web.UI.WebControls.Label lblSEQUENCE;
	protected global::System.Web.UI.WebControls.Label lblITEM_INTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblITEM_NAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_ITEM_CODE;
	protected global::System.Web.UI.WebControls.Label lblSPECIFICATIONS;
	protected global::System.Web.UI.WebControls.Label lblMEASURE_UNIT;
	protected global::System.Web.UI.WebControls.Label lblITEM_TYPE;
	protected global::System.Web.UI.WebControls.Label lblITEM_COLOR;
	protected global::System.Web.UI.WebControls.Label lblNET_PRICE;
	protected global::System.Web.UI.WebControls.Label lblPRICE;
	protected global::System.Web.UI.WebControls.Label lblQTY;
	protected global::System.Web.UI.WebControls.Label lblQUANTITY;
	protected global::System.Web.UI.WebControls.Label lblACTUAL_QTY;
	protected global::System.Web.UI.WebControls.Label lblYKQUANTITY;
	protected global::System.Web.UI.WebControls.Label lblPAYAMOUNT;
	protected global::System.Web.UI.WebControls.Label lblSUPPLY_CODE;
	protected global::System.Web.UI.WebControls.Label lblSUPPLY_NAME;
	protected global::System.Web.UI.WebControls.Label lblPOSITION;
	protected global::System.Web.UI.WebControls.Label lblBARCODE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;
	protected global::System.Web.UI.WebControls.Label lblDESCRIPTION;


       
    }
}
