//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VIP_GRADE {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtGRADE_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtGRADE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtGRADE_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtindate;
		protected global::System.Web.UI.WebControls.TextBox txtoutdate;
		protected global::System.Web.UI.WebControls.TextBox txtLOW_SALES;
		protected global::System.Web.UI.WebControls.TextBox txtTOTAL_SALES;
		protected global::System.Web.UI.WebControls.TextBox txtzsrgrade;
		protected global::System.Web.UI.WebControls.TextBox txtstandrate;
		protected global::System.Web.UI.WebControls.TextBox txtspecialrate;
		protected global::System.Web.UI.WebControls.TextBox txtbirthdayrate;
		protected global::System.Web.UI.WebControls.TextBox txtbirthdayspsrate;
		protected global::System.Web.UI.WebControls.TextBox txtyear_option;
		protected global::System.Web.UI.WebControls.TextBox txtrun;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
