//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.VIP_GRADE {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblGRADE_CODE;
	protected global::System.Web.UI.WebControls.Label lblGRADE_NAME;
	protected global::System.Web.UI.WebControls.Label lblGRADE_TYPE;
	protected global::System.Web.UI.WebControls.Label lblindate;
	protected global::System.Web.UI.WebControls.Label lbloutdate;
	protected global::System.Web.UI.WebControls.Label lblLOW_SALES;
	protected global::System.Web.UI.WebControls.Label lblTOTAL_SALES;
	protected global::System.Web.UI.WebControls.Label lblzsrgrade;
	protected global::System.Web.UI.WebControls.Label lblstandrate;
	protected global::System.Web.UI.WebControls.Label lblspecialrate;
	protected global::System.Web.UI.WebControls.Label lblbirthdayrate;
	protected global::System.Web.UI.WebControls.Label lblbirthdayspsrate;
	protected global::System.Web.UI.WebControls.Label lblyear_option;
	protected global::System.Web.UI.WebControls.Label lblrun;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
