//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SAL_ITEM_NOW_PRICE {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtCompanyCode;
		protected global::System.Web.UI.WebControls.TextBox txtItemNo;
		protected global::System.Web.UI.WebControls.TextBox txtColor;
		protected global::System.Web.UI.WebControls.TextBox txtItemInternalCode;
		protected global::System.Web.UI.WebControls.TextBox txtInternalCodeMean;
		protected global::System.Web.UI.WebControls.TextBox txtAllPrice;
		protected global::System.Web.UI.WebControls.TextBox txtWholeSalePrice;
		protected global::System.Web.UI.WebControls.TextBox txtOncePrice;
		protected global::System.Web.UI.WebControls.TextBox txtMeasureUnit;
		protected global::System.Web.UI.WebControls.TextBox txtLastEdit;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
