//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_USER_DATARIGHT {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMENU_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtMENU_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtMENU_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_MENU_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtUSER_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE_INDEX;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
