//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_USER_DATARIGHT {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMENU_CODE;
	protected global::System.Web.UI.WebControls.Label lblMENU_NAME;
	protected global::System.Web.UI.WebControls.Label lblMENU_UNIT;
	protected global::System.Web.UI.WebControls.Label lblPARENT_MENU_CODE;
	protected global::System.Web.UI.WebControls.Label lblUSER_CODE;
	protected global::System.Web.UI.WebControls.Label lblIMAGE_INDEX;
	protected global::System.Web.UI.WebControls.Label lbltempid;


       
    }
}
