//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_DEPARTMENT {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtINTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_DEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtMANAGER;
		protected global::System.Web.UI.WebControls.TextBox txtTELEPHONE;
		protected global::System.Web.UI.WebControls.TextBox txtADDRESS;
		protected global::System.Web.UI.WebControls.TextBox txtSHOP_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSETTLE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtSIZE;
		protected global::System.Web.UI.WebControls.TextBox txtEMAIL;
		protected global::System.Web.UI.WebControls.TextBox txtFAX;
		protected global::System.Web.UI.WebControls.TextBox txtDISCOUNT;
		protected global::System.Web.UI.WebControls.TextBox txtSHIP;
		protected global::System.Web.UI.WebControls.TextBox txtPPRICE_SHOW;
		protected global::System.Web.UI.WebControls.TextBox txtSALE_METHOD;
		protected global::System.Web.UI.WebControls.TextBox txtALLOW_USED;
		protected global::System.Web.UI.WebControls.TextBox txtSTART_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
