//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_DEPARTMENT {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblINTERNAL_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblDEPARTMENT_NAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_DEPARTMENT_CODE;
	protected global::System.Web.UI.WebControls.Label lblMANAGER;
	protected global::System.Web.UI.WebControls.Label lblTELEPHONE;
	protected global::System.Web.UI.WebControls.Label lblADDRESS;
	protected global::System.Web.UI.WebControls.Label lblSHOP_NAME;
	protected global::System.Web.UI.WebControls.Label lblSETTLE_DATE;
	protected global::System.Web.UI.WebControls.Label lblSIZE;
	protected global::System.Web.UI.WebControls.Label lblEMAIL;
	protected global::System.Web.UI.WebControls.Label lblFAX;
	protected global::System.Web.UI.WebControls.Label lblDISCOUNT;
	protected global::System.Web.UI.WebControls.Label lblSHIP;
	protected global::System.Web.UI.WebControls.Label lblPPRICE_SHOW;
	protected global::System.Web.UI.WebControls.Label lblSALE_METHOD;
	protected global::System.Web.UI.WebControls.Label lblALLOW_USED;
	protected global::System.Web.UI.WebControls.Label lblSTART_DATE;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
