//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_FIXEDASSET {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtFIXEDASSET_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtFIXEDASSET_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtSUPPLY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtOUT_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtPOWER_RATE;
		protected global::System.Web.UI.WebControls.TextBox txtBEGIN_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtEND_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtMEASURE_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtQUANTITY;
		protected global::System.Web.UI.WebControls.TextBox txtFIXEDASSET_STATUS;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPOSITION;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
