//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_SYSCS {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtFullName;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtEmail;
		protected global::System.Web.UI.WebControls.TextBox txtFax;
		protected global::System.Web.UI.WebControls.TextBox txtSHDCNT;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE_LENGTH;
		protected global::System.Web.UI.WebControls.CheckBox chkBillasstock;
		protected global::System.Web.UI.WebControls.TextBox txtMAYLH;
		protected global::System.Web.UI.WebControls.TextBox txtServiceTelphone;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
