//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_SYSCS {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_NAME;
	protected global::System.Web.UI.WebControls.Label lblFullName;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblFax;
	protected global::System.Web.UI.WebControls.Label lblSHDCNT;
	protected global::System.Web.UI.WebControls.Label lblITEM_CODE_LENGTH;
	protected global::System.Web.UI.WebControls.Label lblBillasstock;
	protected global::System.Web.UI.WebControls.Label lblMAYLH;
	protected global::System.Web.UI.WebControls.Label lblServiceTelphone;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
