//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SAL_CUSTOM {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCompanyCode;
		protected global::System.Web.UI.WebControls.TextBox txtCustomerCode;
		protected global::System.Web.UI.WebControls.TextBox txtCustomerLevel;
		protected global::System.Web.UI.WebControls.TextBox txtDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtDiscountGrade;
		protected global::System.Web.UI.WebControls.TextBox txtTradeAmount;
		protected global::System.Web.UI.WebControls.TextBox txtTradeAmountDate;
		protected global::System.Web.UI.WebControls.TextBox txtTradeGrade;
		protected global::System.Web.UI.WebControls.TextBox txtDueAmount;
		protected global::System.Web.UI.WebControls.TextBox txtDueAmountDate;
		protected global::System.Web.UI.WebControls.TextBox txtDueGrade;
		protected global::System.Web.UI.WebControls.TextBox txtDueTime;
		protected global::System.Web.UI.WebControls.TextBox txtDueTimeGrade;
		protected global::System.Web.UI.WebControls.TextBox txtDueTimeDate;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
