//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SAL_CUSTOM {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCompanyCode;
	protected global::System.Web.UI.WebControls.Label lblCustomerCode;
	protected global::System.Web.UI.WebControls.Label lblCustomerLevel;
	protected global::System.Web.UI.WebControls.Label lblDiscount;
	protected global::System.Web.UI.WebControls.Label lblDiscountGrade;
	protected global::System.Web.UI.WebControls.Label lblTradeAmount;
	protected global::System.Web.UI.WebControls.Label lblTradeAmountDate;
	protected global::System.Web.UI.WebControls.Label lblTradeGrade;
	protected global::System.Web.UI.WebControls.Label lblDueAmount;
	protected global::System.Web.UI.WebControls.Label lblDueAmountDate;
	protected global::System.Web.UI.WebControls.Label lblDueGrade;
	protected global::System.Web.UI.WebControls.Label lblDueTime;
	protected global::System.Web.UI.WebControls.Label lblDueTimeGrade;
	protected global::System.Web.UI.WebControls.Label lblDueTimeDate;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
