//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_VEHICLE {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblVehicleID;
	protected global::System.Web.UI.WebControls.Label lblVehicle_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtVehicle_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtMobilePhone;
		protected global::System.Web.UI.WebControls.TextBox txtstandard_area;
		protected global::System.Web.UI.WebControls.TextBox txtReal_area;
		protected global::System.Web.UI.WebControls.TextBox txtweigth;
		protected global::System.Web.UI.WebControls.TextBox txtWithcar;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
