//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_VEHICLE {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblVehicleID;
	protected global::System.Web.UI.WebControls.Label lblVehicle_CODE;
	protected global::System.Web.UI.WebControls.Label lblVehicle_NAME;
	protected global::System.Web.UI.WebControls.Label lblMobilePhone;
	protected global::System.Web.UI.WebControls.Label lblstandard_area;
	protected global::System.Web.UI.WebControls.Label lblReal_area;
	protected global::System.Web.UI.WebControls.Label lblweigth;
	protected global::System.Web.UI.WebControls.Label lblWithcar;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
