//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_CUSTOM {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREDIT_LIMIT;
		protected global::System.Web.UI.WebControls.TextBox txtORG_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_CUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCREDIT_AMOUNT;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_TYPE_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtFULL_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtSALE_MAN;
		protected global::System.Web.UI.WebControls.TextBox txtFAX;
		protected global::System.Web.UI.WebControls.TextBox txtMANAGER;
		protected global::System.Web.UI.WebControls.TextBox txtADDRESS;
		protected global::System.Web.UI.WebControls.TextBox txtTELPHIONE;
		protected global::System.Web.UI.WebControls.TextBox txtZIP;
		protected global::System.Web.UI.WebControls.TextBox txtEMAIL;
		protected global::System.Web.UI.WebControls.TextBox txtHTTP;
		protected global::System.Web.UI.WebControls.TextBox txtVIPCARD_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtVIPCARD_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
