//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_CUSTOM {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREDIT_LIMIT;
	protected global::System.Web.UI.WebControls.Label lblORG_CODE;
	protected global::System.Web.UI.WebControls.Label lblPARENT_CUSTOM_CODE;
	protected global::System.Web.UI.WebControls.Label lblCREDIT_AMOUNT;
	protected global::System.Web.UI.WebControls.Label lblCUSTOM_TYPE_CODE;
	protected global::System.Web.UI.WebControls.Label lblFULL_NAME;
	protected global::System.Web.UI.WebControls.Label lblSALE_MAN;
	protected global::System.Web.UI.WebControls.Label lblFAX;
	protected global::System.Web.UI.WebControls.Label lblMANAGER;
	protected global::System.Web.UI.WebControls.Label lblADDRESS;
	protected global::System.Web.UI.WebControls.Label lblTELPHIONE;
	protected global::System.Web.UI.WebControls.Label lblZIP;
	protected global::System.Web.UI.WebControls.Label lblEMAIL;
	protected global::System.Web.UI.WebControls.Label lblHTTP;
	protected global::System.Web.UI.WebControls.Label lblVIPCARD_CODE;
	protected global::System.Web.UI.WebControls.Label lblVIPCARD_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblCREATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_NAME;
	protected global::System.Web.UI.WebControls.Label lblUPDATE_DATE;
	protected global::System.Web.UI.WebControls.Label lblREMARK;


       
    }
}
