//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_REGISTER {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCOMPANY_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_COMPANY_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtFULL_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtADRESS;
		protected global::System.Web.UI.WebControls.TextBox txtSERVICE_PHONE;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
