//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.SYS_REGISTER {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCOMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblCOMPANY_NAME;
	protected global::System.Web.UI.WebControls.Label lblPARENT_COMPANY_CODE;
	protected global::System.Web.UI.WebControls.Label lblFULL_NAME;
	protected global::System.Web.UI.WebControls.Label lblADRESS;
	protected global::System.Web.UI.WebControls.Label lblSERVICE_PHONE;


       
    }
}
