//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.ORDER_Capacity_chart {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtINTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtBILLDATE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtDEPARTMENT_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtQUANTITY;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
