//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyERP.Web.PUB_ITEM_DA {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtITEM_INTERNAL_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtCUSTOM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NO;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_CODE_old;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_COLOR;
		protected global::System.Web.UI.WebControls.TextBox txtPARENT_ITEM_CODE;
		protected global::System.Web.UI.WebControls.TextBox txtITEM_TYPE;
		protected global::System.Web.UI.WebControls.TextBox txtSPECIFICATIONS;
		protected global::System.Web.UI.WebControls.TextBox txtMEASURE_UNIT;
		protected global::System.Web.UI.WebControls.TextBox txtTYPE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtNET_PRICE;
		protected global::System.Web.UI.WebControls.TextBox txtPRICE;
		protected global::System.Web.UI.WebControls.TextBox txtPOSITION;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE;
		protected global::System.Web.UI.WebControls.TextBox txtIMAGE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtActual_Qty;
		protected global::System.Web.UI.WebControls.TextBox txtBARCODE;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtCREATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_NAME;
		protected global::System.Web.UI.WebControls.TextBox txtUPDATE_DATE;
		protected global::System.Web.UI.WebControls.TextBox txtREMARK;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
